name: publish

on:
  release:
    types: [ released ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install mdbook and mdbook-katex
        run: cargo install mdbook mdbook-katex@0.3.4
          
      - name: Build html
        run: mdbook build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html
